### ISSUE TITLE
Why did this gut functionality

### ISSUE THREAD

**Issue by ketura** [PokeD/PokeAPI-NJ.NET#1]
It's one thing to convert to JSON.NET, but this actually ended up removing other functionality, such as the use of ResourceLists to abstractly enumerate the API.  This should be clearly marked in the readme, so that users are not mislead into thinking it's a 1:1 conversion of the original library, rather than an (incomplete) rewrite.

Honestly it's dishonest to put this up on nuget without that.

**Comment by Aragas** [comment]
Feel free to fix that in README, or implement the functionality yourself
